version: "3.5"
services:
    db:
        image: postgres:alpine
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432

volumes:
    dbdata:

networks:
    default:
        external:
            name: webproxy
