db:
    url: "host=localhost user=postgres dbname=postgres password=114514 sslmode=disable"
server:
    port: "3001"
    cors:
        - "http://localhost:9000"
    firebase_config: "firebase.json"
    access_token_secret: "114514"
