environment: "development"
db:
    provider: "sqlite3"
    url: "database/dev.db"
server:
    port: "3001"
    cors:
        - "http://localhost:3000"
    firebase_config: "./config/firebase/firebase.json"
    access_token_secret: "114514"
